# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- staging

variables:
  netCoreSdkVersion: '3.1.100'
  buildConfiguration: 'Release'
  productVersion: '7.0.0-preview4'

jobs:

- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: $(netCoreSdkVersion)
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
  - script: npm install
  - script: npm run build
  - script: dotnet build ./build/sscms.sln --configuration $(buildConfiguration)
  - script: dotnet publish ./build/src/SSCMS.Web/SSCMS.Web.csproj -r linux-x64 --configuration $(buildConfiguration) -o ./publish/sscms-$(productVersion)-linux-x64 /p:PublishSingleFile=true
  - script: npm run copy-linux-x64
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: './publish/sscms-$(productVersion)-linux-x64' 
      archiveType: 'zip'
      includeRootFolder: false
      archiveFile: './publish/sscms-$(productVersion)-linux-x64/dist/sscms-$(productVersion)-linux-x64.zip'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: './publish/sscms-$(productVersion)-linux-x64/dist' 
      artifactName: 'sscms-$(productVersion)-linux'
