# https://docs.microsoft.com/azure/devops/pipelines

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'siteserver-all.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: 6.10.$(Build.BuildNumber)

steps:
- task: DotNetCoreInstaller@0
  displayName: install dotnet
  inputs:
    version: '3.0.100-preview5-011568'

- task: NuGetToolInstaller@1
  displayName: install nuget
  inputs:
    versionSpec: 
    checkLatest: true

- script: dotnet restore $(solution)
  displayName: dotnet restore

- task: NuGetCommand@2
  displayName: nuget restore
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- script: dotnet pack /p:PackageVersion=$(version)
  displayName: dotnet pack

- task: NodeTool@0
  displayName: install nodejs
  inputs:
    versionSpec: '6.x'

- script: npm install gulp -g
  displayName: install gulp

- script: npm install
  displayName: npm install

- script: gulp build
  displayName: gulp build

- script: nuget pack build/SS.CMS.nuspec
  displayName: nuget pack

- script: gulp zip
  displayName: gulp zip
