# https://docs.microsoft.com/azure/devops/pipelines

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'siteserver-all.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: 6.10.$(Build.BuildNumber)-beta

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '3.0.100-preview5-011568' # replace this value with the version that you need for your project

- script: dotnet restore $(solution)

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- script: dotnet pack /p:PackageVersion=$(version)  # define version variable elsewhere in your pipeline

- task: Gulp@1
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'build'
    enableCodeCoverage: false



